name: nightly build
on:
  push:
    tags:
      - "*nightly"

jobs:
  nightly-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        run: yarn --ignore-scripts
      - name: build the app
        run: yarn nightly
      - uses: "./.github/actions/get-package-infos"
        id: version
      - name: upload macOS app
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.version.outputs.pkgName }}-${{ steps.version.outputs.pkgVersion }}-macos.zip
          path: dist/${{ steps.version.outputs.pkgName }}-${{ steps.version.outputs.pkgVersion }}-mac.zip
  nightly-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: install linux dependencies
        run: sudo apt-get install libudev-dev libusb-1.0-0-dev
      - name: get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: install dependencies
        run: yarn --ignore-scripts
      - name: build the app
        run: yarn nightly
      - uses: "./.github/actions/get-package-infos"
        id: version
      - name: upload linux app
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.version.outputs.pkgName }}-${{ steps.version.outputs.pkgVersion }}-linux.AppImage
          path: dist/${{ steps.version.outputs.pkgName }}-${{ steps.version.outputs.pkgVersion }}-linux-x86_64.AppImage
