name: bundle app
on:
  pull_request:
    types: [ready_for_review]

jobs:
  bundle:
    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: install dependencies
        run: yarn
      - name: build the app
        run: yarn nightly
      - name: upload macOS app
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v1
        with:
          name: lld-macos.zip
          path: dist/ledger-live-desktop-v2-1.0.0-mac.zip
      # - name: upload windows app
      #   if: runner.os == 'Windows'
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: lld-windows.exe
      #     path: dist/ledger-live-desktop-v2-1.0.0-win.exe
      - name: upload linux app
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v1
        with:
          name: lld-linux.AppImage
          path: dist/ledger-live-desktop-v2-1.0.0-linux-x86_64.AppImage
