name: CI
on: [pull_request]

jobs:
  ci-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: install linux dependencies
        run: sudo apt-get install libudev-dev libusb-1.0-0-dev
      - name: install dependencies
        # yarn prepublish is actually run after a normal `yarn install`
        # however since we skip with --ignore-scripts to avoid rebuilding libcore twice
        # we need to run yarn prepublish
        run: |
          yarn --ignore-scripts
          yarn prepublish
      - name: test
        run: yarn ci
  ci-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: install dependencies
        run: |
          yarn --ignore-scripts
          yarn prepublish
      - name: test
        run: yarn ci
  # ci-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@master
  #       with:
  #         node-version: 12.x
  #     - name: install dependencies
  #       run: yarn
  #     - name: rebuild app deps
  #       run: yarn install-deps
  #     - name: install flow-defs
  #       run: yarn flow-typed
  #     - name: test
  #       run: yarn ci
