name: nightly build
on:
  schedule:
    - cron: "0 22 * * 1-5"

jobs:
  nightly-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: install dependencies
        run: yarn
      - name: build the app
        run: yarn nightly
      - uses: "./.github/actions/get-package-infos"
        id: version
      - name: upload macOS app
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.version.outputs.pkgName }}-${{ steps.version.outputs.pkgVersion }}-macos.zip
          path: dist/${{ steps.version.outputs.pkgName }}-${{ steps.version.outputs.pkgVersion }}-mac.zip
  nightly-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: install linux dependencies
        run: sudo apt-get install libudev-dev libusb-1.0-0-dev
      - name: install dependencies
        run: yarn
      - name: build the app
        run: yarn nightly
      - uses: "./.github/actions/get-package-infos"
        id: version
      - name: upload linux app
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.version.outputs.pkgName }}-${{ steps.version.outputs.pkgVersion }}-linux.AppImage
          path: dist/ledger-live-desktop-v2-${{ steps.version.outputs.pkgVersion }}-linux-x86_64.AppImage
